### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by PLudrak** [flet-dev/flet#5810]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

After creating new fresh python venv for my project i get error on import 

### Code sample

<details open><summary>Code</summary>

```python
import flet.map as map
```

</details>

### To reproduce

My app crashes right on the start - import

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

10

### Flet version

0.28.3

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
 File "d:\Python\kuba\web_map\WebMap\main.py", line 4, in <module>
    import flet.map as map
  File "D:\Python\kuba\web_map\Files\.venv\Lib\site-packages\flet\map\__init__.py", line 2, in <module>
    from flet.core.map.map import (
ImportError: cannot import name 'MapPointerDeviceType' from 'flet.core.map.map' (D:\Python\kuba\web_map\Files\.venv\Lib\site-pack\map.py). Did you mean: 'PointerDeviceType'?
```

</details>

### Additional details

It had worked in 0.25.1 version,

**Comment by ndonkoHenri** [comment]
Map-related classes are now to be used through [flet-map](https://docs.flet.dev/map/) package. Read on it and give it a try.
