### ISSUE TITLE
'MatplotlibChart' object has no attribute '_MatplotlibChart__img'

### ISSUE THREAD

**Issue by necromancerWang** [flet-dev/flet#4960]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In flet 0.27.1, when i use "MatplotlibChart" control to plot data, an "AttributeError" was shown.
'MatplotlibChart' object has no attribute '_MatplotlibChart__img'
This error was not shown in flet 0.26.0.

### Code sample

<details open><summary>Code</summary>

```python
import matplotlib
import matplotlib.pyplot as plt

import flet as ft
from flet.matplotlib_chart import MatplotlibChart

matplotlib.use("svg")


def main(page: ft.Page):

    fig, ax = plt.subplots()

    fruits = ["apple", "blueberry", "cherry", "orange"]
    counts = [40, 100, 30, 55]
    bar_labels = ["red", "blue", "_red", "orange"]
    bar_colors = ["tab:red", "tab:blue", "tab:red", "tab:orange"]

    ax.bar(fruits, counts, label=bar_labels, color=bar_colors)

    ax.set_ylabel("fruit supply")
    ax.set_title("Fruit supply by kind and color")
    ax.legend(title="Fruit color")

    page.add(MatplotlibChart(fig, expand=True))


ft.app(target=main)

```

</details>

### To reproduce

The code above can't run in flet 0.27.1

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

windows 11 24H2

### Flet version

0.27.1

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by GF3000** [comment]
Same issue, just appeared after updating from 0.26 -> 0.27

**Comment by necromancerWang** [comment]
The issue is already solved in 0.27.2.

**Comment by shoukewei** [comment]
I have the similar error:
flet --version
0.28.3

AttributeError: module 'flet' has no attribute 'MatplotlibChart'. Did you mean: 'matplotlib_chart'?

Thanks
