### ISSUE TITLE
Rename `Control.on_update` to `Control.before_update`

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2642]
Dismissible example in the documentation doesn't work in Flet 0.20.0

**Code example to reproduce the issue:**

```python
(paste your program here)
```

TypeError: EventHandler.__sync_handler() missing 1 required positional argument: 'e'

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

flet 0.20.0

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

Windows 11

**Comment by ndonkoHenri** [comment]
Please can you fill up the bug/issue template with all necessary details.

**Comment by yunguangli** [comment]
I simply copied the example in the documentation and ran it under Flet 0.20.0 and Windows 11.  Here is the complete error log:

 File "C:\PyProjects\venv\Lib\site-packages\flet_runtime\app.py", line 357, in on_session_created
    session_handler(page)
  File "c:\PyProjects\test.py", line 40, in main
    page.add(
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 315, in add
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 431, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 456, in __prepare_update
    control.build_update_commands(
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 423, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 480, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 480, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 469, in _build_add_commands
    command = self._build_command(False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 497, in _build_command
    self.on_update()
TypeError: EventHandler.__sync_handler() missing 1 required positional argument: 'e'

**Comment by yunguangli** [comment]
python 3.12.1
