### ISSUE TITLE
Nested ResposiveRow doen't work in Flet 0.21 and above

### ISSUE THREAD

**Issue by yunguangli** [flet-dev/flet#2850]
**Description**
I love the ResponsiveRow  control so I have tested it a lot lately.  And I find that a simple nested ResponsiveRow doesn't work from Flet 0.21 and above.  It works quite well at Flet 0.20.2 and below.  Sample attached.  You can comment out and uncomment the video_info line to see the result. 

**Code example to reproduce the issue:**

```
import flet as ft

def main(page: ft.Page):
    page.title = "scrolling ListView"

    lv = ft.ListView(expand=True, spacing=10, padding=20, height=page.height)

    count = 1

    for i in range(0, 60):
        video_short_display = ft.Text(f"Video {i+1}", col={"xs": 12, "sm": 6},)
        video_title = ft.Text("This is the tile")
        video_uploader = ft.Text("uploader name")
        video_upload_time = ft.Text("upload time")
        video_info = ft.ResponsiveRow([video_short_display, ft.Column([video_title, video_uploader, video_upload_time], col={
                                      "xs": 12, "sm": 6}, spacing=1)], ft.MainAxisAlignment.START)
        # video_info = ft.Row([video_short_display, ft.Column([video_title, video_uploader, video_upload_time], col={
        #                               "xs": 12, "sm": 6}, spacing=1)], ft.MainAxisAlignment.START)
        lv.controls.append(
            ft.Container(video_info)
        )
        count += 1

    wide_layout = ft.ResponsiveRow(
        [ft.Container(ft.Text("Title bar"),
                      col={"xs": 12, "sm": 9}),

         ft.Container(content=lv,
                      padding=5,
                      bgcolor=ft.colors.GREEN,
                      col={"xs": 12, "sm": 3},
                      border_radius=10,
                      expand=True,
                      )
         ],
        expand=True,

    )

    page.add(wide_layout)

ft.app(target=main)

```

**Describe the results you received:**
If Flet 0.21 and above is used. I have these errors:

Unhandled error processing page session : Traceback (most recent call last):
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_runtime\app.py", line 242, in on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "C:\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\layout_test\test.py", line 132, in main
    page.add(wide_layout)
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 314, in add      
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 402, in __update 
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\page.py", line 415, in __prepare_update
    control.build_update_commands(
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 446, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 514, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 514, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 514, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 503, in _build_add_commands
    command = self._build_command(False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 531, in _build_command
    self.before_update()
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\responsive_row.py", line 139, in before_update
    self._set_attr_json("columns", self.__columns)
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 133, in _set_attr_json
    nv = self._convert_attr_json(value)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\control.py", line 139, in _convert_attr_json
    json.dumps(value, cls=EmbedJsonEncoder, separators=(",", ":"))
  File "C:\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\embed_json_encoder.py", line 43, in encode
    return super().encode(self._convert_enums(o))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Documents\PyProjects\venv\Lib\site-packages\flet_core\embed_json_encoder.py", line 40, in default
    return self._convert_enums(obj.__dict__)
                               ^^^^^^^^^^^^
AttributeError: 'mappingproxy' object has no attribute '__dict__'. Did you mean: '__dir__'?

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
0.21.1
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:
Windows 11
Python 3.12.1

**Additional environment details:**

**Comment by burhansvural** [comment]
You write wrong and incomplete codes
```python
"""
Nested ResposiveRow doen't work in Flet 0.21 and above #2850
Nested ResposiveRow, Flet 0.21 ve üzeri sürümlerde çalışmıyor #2850
========================================================================
Description
I love the ResponsiveRow control so I have tested it a lot lately.
And I find that a simple nested ResponsiveRow doesn't work from Flet 0.21 and above.
It works quite well at Flet 0.20.2 and below.
Sample attached. You can comment out and uncomment the video_info line to see the result.
ResponsiveRow kontrolünü seviyorum bu yüzden son zamanlarda onu çok fazla test ettim.
Ve basit bir yuvalanmış ResponsiveRow'un Flet 0.21 ve üzeri sürümlerde çalışmadığını buldum.
Flet 0.20.2 ve altında oldukça iyi çalışıyor.
Örnek ektedir.
Sonucu görmek için video_info satırına yorum yapabilir veya yorumu kaldırabilirsiniz.
======================================================================================
44. satirda resposiveRow için 
ft.MainAxisAlignment.START demiş ama önüne alignment= ifadesini eklememiş.
"""

import flet as ft

def main(page: ft.Page):
    page.title = "scrolling ListView"
    print(f"page.height = {page.height}")
    lv = ft.ListView(expand=True, spacing=10, padding=5, height=page.window_height)

    count = 1

    for i in range(0, 60):
        video_short_display = ft.Text(f"Video {i+1}", col={"xs": 12, "sm": 6},)
        video_title = ft.Text("This is the tile")
        video_uploader = ft.Text("uploader name")
        video_upload_time = ft.Text("upload time")
        video_info = ft.ResponsiveRow(
            controls=[
                video_short_display,
                ft.Column(
                    controls=[
                        video_title,
                        video_uploader,
                        video_upload_time
                        ],
                    col={"xs": 12, "sm": 6},
                    spacing=1
                )
            ],
            alignment=ft.MainAxisAlignment.START)
        
        lv.controls.append(
            ft.Container(video_info)
        )
        count += 1

    wide_layout = ft.ResponsiveRow(
        controls=[
            ft.Container(
                content=ft.Text("Title bar"),
                col={"xs": 12, "sm": 9}
                ),

            ft.Container(
                content=lv,
                padding=5,bgcolor=ft.colors.GREEN,
                col={"xs": 12, "sm": 3},
                border_radius=10,
                expand=True,
                )
         ],
        expand=True,

    )

    page.add(wide_layout)

ft.app(target=main)
```

**Comment by yunguangli** [comment]
Ah... ok. forgot to write alignment.... problem resolved. But why 0.20.2 and below worked? Interesting
