### ISSUE TITLE
bug: filepicker not working on macos monterey 12 and Android 11

### ISSUE THREAD

**Issue by Araujo-Gabriel593** [flet-dev/flet#5753]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

On macOS the filepicker doesn't open. On android it opens but show an error when I choose a photo.

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page):
    def pick_files_result(e: ft.FilePickerResultEvent):
        if e.files:
            print("Ficheiro(s) selecionado(s):", [f.path for f in e.files])
        else:
            print("Nenhum ficheiro selecionado.")

    file_picker = ft.FilePicker(on_result=pick_files_result)
    page.overlay.append(file_picker)

    def open_picker(e):
        print("DEBUG: Botão clicado, a chamar pick_files...")
        file_picker.pick_files(
            allow_multiple=True, # Vamos permitir múltiplos para teste
            dialog_title="Teste do Seletor"
        )
        page.update()
        print("DEBUG: Chamada a pick_files concluída.")

    page.title = "Teste do FilePicker"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.add(
        ft.ElevatedButton("Abrir Seletor de Ficheiros", on_click=open_picker)
    )

ft.app(target=main)

```

</details>

### To reproduce

Run the code on android: flet run --android. 
Scan QR code and open the app.
Click the button and choose image.
Error appears  

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Monterey 12

### Flet version

0.28.3

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
console
Task exception was never retrieved

future: <Task finished name='Task-72' coro=<FletApp.__on_event() done, defined at /Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet_web/fastapi/flet_app.py:113> exception=TypeError("FilePickerFile.__init__() missing 1 required positional argument: 'id'")>

Traceback (most recent call last):

  File "/Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet_web/fastapi/flet_app.py", line 119, in __on_event

    await session.on_event_async(

        Event(e.eventTarget, e.eventName, e.eventData)

    )

  File "/Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet/core/page.py", line 866, in on_event_async

    await handler(ce)

  File "/Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet/core/event_handler.py", line 17, in fn

    ce = self.__result_converter(e)

  File "/Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet/core/file_picker.py", line 128, in convert_result_event_data

    self.__result = FilePickerResultEvent(e)

                    ~~~~~~~~~~~~~~~~~~~~~^^^

  File "/Users/macbookair/Projects/app-receita/.venv/lib/python3.13/site-packages/flet/core/file_picker.py", line 54, in __init__

    self.files.append(FilePickerFile(**fd))

                      ~~~~~~~~~~~~~~^^^^^^

TypeError: FilePickerFile.__init__() missing 1 required positional argument: 'id'`


```

</details>

### Additional details

I tested flet version 0.28.2 and does open the file picker on mac but don't choose the image. On android is still the same.

**Comment by StianHanssen** [comment]
I want add that I think this is a regression on MacOS at least. My colleagues who use MacOS reported the file picker didn't work after I upgraded from 2.28.2 to 2.28.3.

They reported the file picker button didn't react at all in 2.28.3.

**Comment by Boaz-Maroko** [comment]
The same exact issue happens on Android 15 and flet v0.28.3

**Comment by ndonkoHenri** [comment]
Can you please try the [latest pre-release](https://flet.dev/blog/introducing-flet-1-0-alpha/#trying-flet-10-alpha) and let know if the issue still happens? 

See FilePicker code examples here: https://docs.flet.dev/controls/filepicker/
